In [ ]:
# this notebook is based off of the problems found at https://www.codinginterview.com/google-interview-questions


In [ ]:
# Arrays

In [32]:
# Sum of two values

#this solution works by computing what number we need from the target value and the value we're currently looking at in the array


#so we can generate a random array
import numpy as np
from sys import exit

#ask user for array length
arr_input = input("How large should the array be?: ")

#make sure its an integer
try:
    arr_size = int(arr_input)
except ValueError:
    print("that's not an int you mook!")
    raise

#create array of chosen length
numpy_arr = np.random.randint(1000, size= arr_size)
#convert numpy to python list/array so we can use pop...
arr = list(numpy_arr)

#print the array (useful for actually verifying if the program is correct...)
print("For the array: {}".format(arr))

#get the target value from the user
target_input = input("What number should I look for?: ")

#make sure target is an integer
try:
    target_value = int(target_input)
except ValueError:
    print("that's not an int you mook!")
    raise


#to track if found for output message below
found = False

#for every element in the array
for i in range(0, len(arr)):
    
    #get the target value minus the first number (the indexed number) and 
    # remove it from the list to prevent the possibility of duplicate ie [3,2,1] looking for 6 resuling in 0,0
    temp = target_value - arr.pop(0)
    
    #check if our temp value is in the array (i.e, our current index has a counterpart that adds to the target value)
    if temp in arr:
        #i is where the arr.pop happens, the second value is +1 to account for the pop and plus i to account for previous pops
        print("indexes {} and {} add up to {}".format(i, i + arr.index(temp) + 1, target_value))
        found = True

#if not found, inform the user
if found == False:
    print("I couldn't find any two indexes in the array that add up to {}".format(target_value))
    


How large should the array be?:  2


For the array: [889, 847]


What number should I look for?:  1


I couldn't find any two values in the array that add up to 1


In [49]:
#move zeroes to the left

#this solution works by having two scrolling indexs beginning at the end of the array that move left until they hit the front of the array
# they begin by being side by size i.e. index and index+1, but for every zero they encounter the gap between them is increased.
# the last index should always be pointing to a zero

arr_input = input("How large should the array be?: ")

#make sure its an integer
try:
    arr_size = int(arr_input)
except ValueError:
    print("that's not an int you mook!")
    raise

    
range_input = input("What should the range of values be? (0 to ___?): ")

#make sure its an integer
try:
    range_value = int(range_input)+1
except ValueError:
    print("that's not an int you mook!")
    raise
    

arr = np.random.randint(range_value, size= arr_size)

index_end = len(arr)-1
index_front = index_end-1

#while we haven't touched the first element in the array
while index_front != -1:
    #switch cases!
    
    #if the end of our window rests on a zero, we may hunt for a number to replace it with...
    if arr[index_end] == 0: 
        if arr[index_front] != 0: #if we have found a number to replace it with...
            
            #swap them!
            temp = arr[index_end]
            arr[index_end] = arr[index_front]
            arr[index_front] = temp
            
            # and advance the end of our window since it no longer points to a zero
            index_end-=1
            
        elif arr[index_front] == 0: #if we haven't found a number yet...
            index_front-=1 #increase the size of the window!

    #if the end index is NOT a zero... we want it to be
    elif arr[index_end] != 0: 
        
        # advance the end index until it hits a zero OR it is next to the front index
        
        if index_end-1 == index_front: #arr indexes side by side
            #shift them both up by 1!
            index_end-=1
            index_front-=1
        else:
            #advance the end of the window to find a zero!
            index_end-=1
    print(arr)
    
    

How large should the array be?:  10
What should the range of values be? (0 to ___?):  2


[0 1 1 2 1 0 0 2 0 1]
[0 1 1 2 1 0 0 2 0 1]
[0 1 1 2 1 0 0 0 2 1]
[0 1 1 2 1 0 0 0 2 1]
[0 1 1 2 1 0 0 0 2 1]
[0 1 1 2 1 0 0 0 2 1]
[0 1 1 2 0 0 0 1 2 1]
[0 1 1 2 0 0 0 1 2 1]
[0 1 1 0 0 0 2 1 2 1]
[0 1 1 0 0 0 2 1 2 1]
[0 1 0 0 0 1 2 1 2 1]
[0 1 0 0 0 1 2 1 2 1]
[0 0 0 0 1 1 2 1 2 1]
[0 0 0 0 1 1 2 1 2 1]
[0 0 0 0 1 1 2 1 2 1]


In [ ]:
# delete node with given key

#just basic delete... but we need a few functions of a linked list added first.
# these are shamelessly copied from my implementation found under python/data_structures/doubly_linked_list
class Node:

    #here we create an init function for inception of a node. This includes a previous pointer and a next pointer
    def __init__(self, value):
        self.value = value
        self.prev = None
        self.next = None
        
    #here we create a representation function for displaying the node if called upon
    def __repr__(self):
        return self.value

class doubly_linked_list:
    
    #another init for the head of the list. This includes a counter for elements in the list and a tail pointer for finding the end quickly
    def __init__(self):
        self.head = None
        self.tail = None
        self.element_count = 0
     
    #here we have a representation function for displaying the linked list itself, it works by traversing the list and storing the value of each node in an array
    #and then joining the array together separated by arrows ( -> )
    def __repr__(self):
        cur = self.head
        nodes = []

        while cur != None:
            nodes.append(str(cur.value))
            cur = cur.next

        nodes.append("None")

        return " -> ".join(nodes)
    
 #insert the node at the head of the linked list
    def insert_at_head(self, value):
        
        #i've changed the following up because I did not want to declare a bunch of nodes..
        
        
        
        
        if new_node != None:
            self.element_count+=1
            if self.head == None: #if no head exists
                #set the head and tail to be the new node
                self.head = new_node
                self.tail = new_node

            else: #if there is a current head
                #point the new head's next to be the current head
                new_node.next = self.head
                #point the current head's previous to be the new head
                self.head.prev = new_node
                #reassign the list's head pointer to be the new head
                self.head = new_node

    def delete_node_with_value(self, target_value):
        pos = 0
        cur = self.head
        deleted = False

        #while not at target
        while cur != None and deleted != True:

            if cur.value == target_value:

                self.element_count-=1
                deleted = True

                #if previous, patch it up
                if cur.prev != None:
                    cur.prev.next = cur.next
                else: #must be the head so we have a new head
                    self.head = cur.next

                #if next, patch it up
                if cur.next != None:
                    cur.next.prev = cur.prev
                else: #must be the tail so we have a new tail
                    self.tail = cur.prev



            cur = cur.next #push position forwards

    def delete_all_with_value(self, target_value):
        pos = 0
        cur = self.head

        #while not at target
        while cur != None:

            if cur.value == target_value:

                temp = cur.next

                self.element_count-=1

                #if previous, patch it up
                if cur.prev != None:
                    cur.prev.next = cur.next
                else: #must be the head so we have a new head
                    self.head = cur.next

                #if next, patch it up
                if cur.next != None:
                    cur.next.prev = cur.prev
                else: #must be the tail so we have a new tail
                    self.tail = cur.prev

                cur = temp
            else:
                cur = cur.next #push position forwards
                
node1 =
node2 = 
node3 =
node4 =